baseurl = "https://www.teky.io"
languageCode = "en-us"
title = "TEKY SRL"

[[menu.en_menu]]
    name = "Technology"
    url = "twu"
    weight = -300
[[menu.en_menu]]
    name = "About Us"
    url = "about"
    weight = -200
[[menu.en_menu]]
    name = "Contact"
    url = "contact"
    weight = -100
[[menu.es_menu]]
    name = "Nuestra Historia"
    url = "about"
    weight = -200
[[menu.es_menu]]
    name = "Contacto"
    url = "contact"
    weight = -100
